# Generated by Django 3.1.7 on 2021-04-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210408_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ('rank', 'role', 'pk')},
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.TextField(blank=True)),
                ('rank', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('rank', 'role', 'pk'),
            },
        ),
    ]
